
hwi_oauth:

    connect: ~
        # confirmation: true # should show confirmation page or not
        # registration_form_handler: my_registration_form_handler
        # registration_form: fos_user.registration.form
        # account_connector: my_link_provider # can be the same as your user provider

    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            facebook: facebookUid
            google: gplusUid
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%client_facebook_id%"
            client_secret:       "%client_facebook_secret%"
            scope:               ""
        google:
            type:                google
            client_id:           "%client_google_id%"
            client_secret:       "%client_google_secret%"
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
    # here you will add one (or more) configurations for resource owners
    # 
    http_client:
        timeout:       5
        verify_peer:   false
        ignore_errors: true
        max_redirects: 5
