hwi_oauth:
    resource_owners:
        github:
            type:                github
            client_id:           %client_github_id%
            client_secret:       %client_github_secret%
            scope:               "user:email"
            options:
                csrf:            true

        google:
            type:                google
            client_id:           %client_google_id%
            client_secret:       %client_google_secret%
            scope:               "https://www.googleapis.com/auth/plus.login"
            # user_response_class: \Our\Custom\Response\Class
            paths:
                email:           email
                profilepicture:  picture
            options:
                access_type:     offline

        facebook:
            type:                facebook
            client_id:           %client_facebook_id%
            client_secret:       %client_facebook_secret%
            scope:               ""

        twitter:
            type:                twitter
            client_id:           %client_twitter_id%
            client_secret:       %client_twitter_secret%
            scope:               ""

    firewall_name: main

    fosub:
        # try 30 times to check if a username is available (foo, foo1, foo2 etc)
        username_iterations: 30

        # mapping between resource owners (see below) and properties
        properties:
            github: githubId
            google: gplusUid
            facebook: facebookUid
            twitter: twitterUid

    # if you want to use 'connect' and do not use the FOSUB integration, configure these separately
    connect: ~
#        confirmation: true # should show confirmation page or not
#        registration_form_handler: my_registration_form_handler
#        registration_form: my_registration_form
#        account_connector: my_link_provider # can be the same as your user provider

    # optional HTTP Client configuration
    http_client:
        timeout:       5
        verify_peer:   false
        ignore_errors: true
        max_redirects: 5

    # allows to switch templating engine for bundle views
    #templating_engine: "php"