sonata_admin:
    title:      EnjoyLearning
    # title_logo: bundles/tncyschool/img/logo.jpg
    templates:
        search:              SonataAdminBundle:Core:search.html.twig
        search_result_block: SonataAdminBundle:Block:block_search_result.html.twig
        layout:  SonataAdminBundle::layout.html.twig
    security:
        handler: sonata.admin.security.handler.role
        # acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]
    dashboard:
        groups:
            tncyschool.admin.group.user:
                label: User
                label_catalogue: TNCYSchoolBundle
                icon: '<i class="fa fa-user"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.student
                    - sonata.user.admin.teacher
                    - sonata.user.admin.group
            tncyschool.admin.group.school:
                label: School
                label_catalogue: TNCYSchoolBundle
                icon: '<i class="fa fa-briefcase"></i>'
                items:
                    - sonata.admin.schoolclass
                    # - sonata.admin.subject
                    # - sonata.admin.schoolresult
                    - sonata.admin.school
                    - sonata.admin.lesson
                    - sonata.admin.homework
            sonata.admin.group.content:
                label:           Exercice
                label_catalogue: TNCYSchoolBundle
                icon:            '<i class="fa fa-file-word-o "></i>'
                items:
                    - sonata.admin.song
                    - sonata.admin.memory
                    #- sonata.admin.memoryitem
            sonata.admin.group.exercice:
                label:           Blog
                label_catalogue: TNCYSchoolBundle
                icon:            '<i class="fa fa-th"></i>'
                items:
                    - sonata.news.admin.comment
                    - sonata.news.admin.post
                    - sonata.media.admin.media
                    - sonata.media.admin.gallery
            # tncyschool.admin.group.classification:
            #     label: Classification
            #     label_catalogue: TNCYSchoolBundle
            #     icon: '<i class="fa fa-cogs"></i>'
            #     items:
            #         - sonata.classification.admin.category
            #         - sonata.classification.admin.collection
            #         - sonata.classification.admin.tag
            # tncyschool.admin.group.media:
            #     label: Media
            #     label_catalogue: TNCYSchoolBundle
            #     icon: '<i class="fa fa-picture-o"></i>'
            #     items:
            #         - sonata.media.admin.media
            #         - sonata.media.admin.gallery
            #         - sonata.media.admin.gallery_has_media

        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
            -
                position: right
                type: sonata.block.service.text
                settings:
                    content: >
                        <h2>Welcome to the Sonata Admin</h2>
                        <p>This is a <code>sonata.block.service.text</code> from the Block
                        Bundle, you can create and add new block in these area by configuring
                        the <code>sonata_admin</code> section.</p> <br /> For instance, here
                        a RSS feed parser (<code>sonata.block.service.rss</code>):


sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        # Your other blocks
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes
        sonata.admin.block.search_result:
            contexts: [admin]
        sonata.admin.block.filter:
            contexts: [admin]

sonata_core: ~
