services:
    sonata.admin.schoolclass:
        class: TNCY\SchoolBundle\Admin\SchoolClassAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "School", label: "SchoolClass" }
        arguments:
            - ~
            - TNCY\SchoolBundle\Entity\SchoolClass
            - ~
        calls:
            - [ setTranslationDomain, [TNCYSchoolBundle]]
    sonata.admin.subject:
        class: TNCY\SchoolBundle\Admin\SubjectAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "School", label: "Subject" }
        arguments:
            - ~
            - TNCY\SchoolBundle\Entity\Subject
            - ~
        calls:
            - [ setTranslationDomain, [TNCYSchoolBundle]]
    sonata.admin.schoolresult:
        class: TNCY\SchoolBundle\Admin\SchoolResultAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "School", label: "SchoolResult" }
        arguments:
            - ~
            - TNCY\SchoolBundle\Entity\SchoolResult
            - ~
        calls:
            - [ setTranslationDomain, [TNCYSchoolBundle]]

    sonata.user.admin.student:
        class: TNCY\SchoolBundle\Admin\StudentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "School", label: "Student" }
        arguments:
            - ~
            - TNCY\SchoolBundle\Entity\Student
            - ~
        calls:
            - [ setTranslationDomain, [TNCYSchoolBundle]]
    sonata.user.admin.teacher:
        class: TNCY\SchoolBundle\Admin\TeacherAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "School", label: "Teacher" }
        arguments:
            - ~
            - TNCY\SchoolBundle\Entity\Teacher
            - ~
        calls:
            - [ setTranslationDomain, [TNCYSchoolBundle]]
    sonata.admin.school:
        class: TNCY\SchoolBundle\Admin\SchoolAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "School", label: "School" }
        arguments:
            - ~
            - TNCY\SchoolBundle\Entity\School
            - ~
        calls:
            - [ setTranslationDomain, [TNCYSchoolBundle]]

    sonata.admin.lesson:
        class: TNCY\SchoolBundle\Admin\LessonAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "School", label: "Lesson" }
        arguments:
            - ~
            - TNCY\SchoolBundle\Entity\Lesson
            - ~
        calls:
            - [ setTranslationDomain, [TNCYSchoolBundle]]
            - [ setSecurityContext , [@security.context]]