tncy_school_index:
    path:     /
    defaults: { _controller: TNCYSchoolBundle:Default:index }

tncy_school_contact:
    path:     /contact
    defaults: { _controller: TNCYSchoolBundle:Default:contact }

tncy_school_news:
    path:     /news
    defaults: { _controller: TNCYSchoolBundle:Default:news }

tncy_school_about:
    path:     /about
    defaults: { _controller: TNCYSchoolBundle:Default:about }
tncy_school_dashboard:
    path:     /dashboard
    defaults: { _controller: TNCYSchoolBundle:Default:dashboard }

#exercice
tncy_school_memory:
    path:     /exercice/memory
    defaults: { _controller: TNCYSchoolBundle:Exercice:memory }


#profile
tncy_school_profile:
    path:     /user/{id}
    defaults: { _controller: TNCYSchoolBundle:Profile:user }
tncy_school_github:
    path:     /github/{id}
    defaults: { _controller: TNCYSchoolBundle:Profile:githubUser }
tncy_school_facebook:
    path:     /facebook/{id}
    defaults: { _controller: TNCYSchoolBundle:Profile:facebookUser }
tncy_school_marks:
    path:     /marks/{id}
    defaults: { _controller: TNCYSchoolBundle:Profile:marks }

