# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    # my_user_provider.class: Application\Sonata\UserBundle\Entity\FOSUBUserProvider

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.twig_extension:
        class: TNCY\SchoolBundle\Twig\TNCYSchoolExtension
        public: true
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }

    # my_user_provider:
    #     class: "%my_user_provider.class%"
    #     #this is the place where the properties are passed to the UserProvider - see config.yml
    #     arguments: [@fos_user.user_manager,{facebook: facebookUid, google: gplusUid }]