services:
    sonata.admin.schoolclass:
        class: "TNCY\\SchoolBundle\\Admin\\SchoolClassAdmin"
        tags:
            - { name: sonata.admin, manager_type: orm, group: "School", label: "SchoolClass" }
        arguments:
            - ~
            - "TNCY\\SchoolBundle\\Entity\\SchoolClass"
            - ~
        calls:
            - [ setTranslationDomain, [TNCYSchoolBundle]]
    # sonata.admin.subject:
    #     class: TNCY\\SchoolBundle\\Admin\\SubjectAdmin
    #     tags:
    #         - { name: sonata.admin, manager_type: orm, group: "School", label: "Subject" }
    #     arguments:
    #         - ~
    #         - TNCY\\SchoolBundle\\Entity\\Subject
    #         - ~
    #     calls:
    #         - [ setTranslationDomain, [TNCYSchoolBundle]]
    # sonata.admin.schoolresult:
    #     class: TNCY\\SchoolBundle\\Admin\\SchoolResultAdmin
    #     tags:
    #         - { name: sonata.admin, manager_type: orm, group: "School", label: "SchoolResult" }
    #     arguments:
    #         - ~
    #         - TNCY\\SchoolBundle\\Entity\\SchoolResult
    #         - ~
    #     calls:
    #         - [ setTranslationDomain, [TNCYSchoolBundle]]

    sonata.user.admin.student:
        class: "TNCY\\SchoolBundle\\Admin\\StudentAdmin"
        tags:
            - { name: sonata.admin, manager_type: orm, group: "School", label: "Student" }
        arguments:
            - ~
            - "TNCY\\SchoolBundle\\Entity\\Student"
            - ~
        calls:
            - [ setTranslationDomain, [TNCYSchoolBundle]]
    sonata.user.admin.teacher:
        class: "TNCY\\SchoolBundle\\Admin\\TeacherAdmin"
        tags:
            - { name: sonata.admin, manager_type: orm, group: "School", label: "Teacher" }
        arguments:
            - ~
            - "TNCY\\SchoolBundle\\Entity\\Teacher"
            - ~
        calls:
            - [ setTranslationDomain, [TNCYSchoolBundle]]
    sonata.admin.school:
        class: "TNCY\\SchoolBundle\\Admin\\SchoolAdmin"
        tags:
            - { name: sonata.admin, manager_type: orm, group: "School", label: "School" }
        arguments:
            - ~
            - "TNCY\\SchoolBundle\\Entity\\School"
            - ~
        calls:
            - [ setTranslationDomain, [TNCYSchoolBundle]]

    sonata.admin.lesson:
        class: "TNCY\\SchoolBundle\\Admin\\LessonAdmin"
        tags:
            - { name: sonata.admin, manager_type: orm, group: "School", label: "Lesson" }
        arguments:
            - ~
            - "TNCY\\SchoolBundle\\Entity\\Lesson"
            - ~
        calls:
            - [ setTranslationDomain, [TNCYSchoolBundle]]
            - [ setSecurityToken , [@security.token_storage]]

    sonata.admin.song:
        class: "TNCY\\SchoolBundle\\Admin\\ExSongAdmin"
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Exercice", label: "Song" }
        arguments:
            - ~
            - "TNCY\\SchoolBundle\\Entity\\Song"
            - ~
        calls:
            - [ setTranslationDomain, [TNCYSchoolBundle]]
            - [ setSecurityToken , [@security.token_storage]]
            - [ setContainer, [@service_container]]
    sonata.admin.topic:
        class: "TNCY\\SchoolBundle\\Admin\\VocTopicAdmin"
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Exercice", label: "VocTopic" }
        arguments:
            - ~
            - "TNCY\\SchoolBundle\\Entity\\VocTopic"
            - ~
        calls:
            - [ setTranslationDomain, [TNCYSchoolBundle]]

    sonata.admin.memory:
        class: "TNCY\\SchoolBundle\\Admin\\ExMemoryAdmin"
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Exercice", label: "Memory" }
        arguments:
            - ~
            - "TNCY\\SchoolBundle\\Entity\\Memory"
            - ~
        calls:
            - [ setTranslationDomain, [TNCYSchoolBundle]]

    sonata.admin.memoryitem:
        class: "TNCY\\SchoolBundle\\Admin\\ExMemoryItemAdmin"
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Exercice", label: "MemoryItem" }
        arguments:
            - ~
            - "TNCY\\SchoolBundle\\Entity\\MemoryItem"
            - ~
        calls:
            - [ setTranslationDomain, [TNCYSchoolBundle]]

    sonata.admin.matchword:
        class: "TNCY\\SchoolBundle\\Admin\\ExMatchWordAdmin"
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Exercice", label: "Match" }
        arguments:
            - ~
            - "TNCY\\SchoolBundle\\Entity\\MatchWord"
            - ~
        calls:
            - [ setTranslationDomain, [TNCYSchoolBundle]]

    sonata.admin.match:
        class: "TNCY\\SchoolBundle\\Admin\\ExMatchAdmin"
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Exercice", label: "Match" }
        arguments:
            - ~
            - "TNCY\\SchoolBundle\\Entity\\ExerciceMatch"
            - ~
        calls:
            - [ setTranslationDomain, [TNCYSchoolBundle]]
            
    sonata.admin.vocword:
        class: "TNCY\\SchoolBundle\\Admin\\ExVocWordAdmin"
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Exercice", label: "VocWord" }
        arguments:
            - ~
            - "TNCY\\SchoolBundle\\Entity\\VocWord"
            - ~
        calls:
            - [ setTranslationDomain, [TNCYSchoolBundle]]

    sonata.admin.homework:
        class: "TNCY\\SchoolBundle\\Admin\\HomeworkAdmin"
        tags:
            - { name: sonata.admin, manager_type: orm, group: "School", label: "Homework" }
        arguments:
            - ~
            - "TNCY\\SchoolBundle\\Entity\\Homework"
            - ~
        calls:
            - [ setTranslationDomain, [TNCYSchoolBundle]]
            - [ setSecurityToken , [@security.token_storage]]
            - [ setTwig , [@templating]]
            - [ setMailer , [@mailer]]
            - [ setTemplate, [edit, TNCYSchoolBundle:Admin:homework_admin.html.twig]]

